---
abstract: 'Low-Fat Full-Flavored Data Modeling and Validation Framework'
author:
  - 'Al Newkirk <awncorp@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Validation-Class
requires:
  Array::Unique: 0
  Carp: 0
  Hash::Flatten: 0
  Hash::Merge: 0
  Module::Find: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Validation-Class
  homepage: http://ana.io/
  repository: http://github.com/alnewkirk/Validation-Class.git
version: 5.95
