---
abstract: 'Self-Validating Object System and Data Validation Framework'
author:
  - 'Al Newkirk <anewkirk@ana.io>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Validation-Class
requires:
  Carp: 0
  Hash::Flatten: 0
  Hash::Merge: 0
  Module::Find: 0
  Module::Runtime: 0
  utf8: 0
resources:
  bugtracker: https://github.com/alnewkirk/Validation-Class/issues
  homepage: https://github.com/alnewkirk/Validation-Class
  repository: http://github.com/alnewkirk/Validation-Class.git
version: 7.66
