---
abstract: 'Powerful Data Validation Framework'
author:
  - 'Al Newkirk <anewkirk@ana.io>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Validation-Class
requires:
  Class::Forward: 0
  Hash::Flatten: 0
  Hash::Merge: 0
  List::MoreUtils: 0
  Module::Find: 0
  Module::Runtime: 0
resources:
  bugtracker: https://github.com/alnewkirk/Validation-Class/issues
  homepage: http://search.cpan.org/dist/Validation-Class/
  repository: git://github.com/alnewkirk/Validation-Class.git
version: 7.900018
