---
abstract: 'Centralized Input Validation for Any Application'
author:
  - 'Al Newkirk <awncorp@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Validation-Class
requires:
  Array::Unique: 0
  Carp: 0
  Hash::Flatten: 0
  Module::Find: 0
  Moose: 0
  MooseX::Traits: 0
  Scalar::Util: 0
version: 2.4.4
